# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElysiumStatus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseMessaging', '1.2.1'

  # Pods for ElysiumStatus

  target 'ElysiumStatusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
